# Generated by Django 4.0.4 on 2022-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'تم تاریک'), ('light', 'تم روشن'), ('byhour', 'بر طبق ساعت')], default='byhour', max_length=10),
        ),
    ]
