# Generated by Django 3.2.5 on 2022-02-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_username_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
