# Generated by Django 3.2.5 on 2022-02-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodAccount',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(null=True)),
                ('level', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Codm/static/account_pictures')),
                ('region', models.CharField(choices=[('220', 'Iran'), ('360', 'India'), ('560', 'Europe')], default='IR', max_length=3)),
                ('cp', models.IntegerField(blank=True, default=0, null=True)),
                ('c', models.IntegerField(blank=True, default=0, null=True)),
                ('multi_ranked', models.CharField(blank=True, max_length=200, null=True)),
                ('battle_ranked', models.CharField(blank=True, max_length=200, null=True)),
                ('battle_pass', models.TextField(blank=True, max_length=900, null=True)),
                ('description', models.TextField(blank=True, max_length=900, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='w4p', max_length=10)),
                ('final_status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='w4p', max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('factor_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('activision', 'Activision'), ('facebook', 'Facebook'), ('gmail', 'Gmail'), ('apple_id', 'Apple_ID'), ('line', 'Line')], default='Activision', max_length=10)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
            ],
        ),
    ]
