# Generated by Django 3.2.5 on 2022-01-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodAccount',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('region', models.CharField(choices=[('IR', 'Iran'), ('IN', 'India'), ('EU', 'Europe')], default='IR', max_length=2)),
                ('activision', models.BooleanField(default=True)),
                ('gmail', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('line', models.BooleanField(default=False)),
                ('apple', models.BooleanField(default=False)),
                ('cp', models.IntegerField(blank=True, default=0, null=True)),
                ('c', models.IntegerField(blank=True, default=0, null=True)),
                ('multi_ranked', models.CharField(blank=True, max_length=200, null=True)),
                ('battle_ranked', models.CharField(blank=True, max_length=200, null=True)),
                ('battle_pass', models.TextField(blank=True, max_length=900, null=True)),
                ('description', models.TextField(blank=True, max_length=900, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='available', max_length=10)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
            ],
        ),
    ]
