# Generated by Django 3.2.5 on 2022-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x0000020F0AD01D60>'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x0000020F0AD01D60>'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x0000020F0AD01D60>'),
        ),
    ]
