# Generated by Django 3.2.5 on 2022-01-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codaccount',
            name='activision',
        ),
        migrations.RemoveField(
            model_name='codaccount',
            name='apple',
        ),
        migrations.RemoveField(
            model_name='codaccount',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='codaccount',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='codaccount',
            name='line',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('activision', 'Activision'), ('gmail', 'Gmail'), ('apple_id', 'Apple_ID'), ('line', 'Line')], default='Activision', max_length=10)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
            ],
        ),
    ]
