# Generated by Django 3.2.5 on 2022-01-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0002_auto_20220123_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='codaccount',
            name='final_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='codaccount',
            name='image',
            field=models.ImageField(null=True, upload_to='static/account_pictures'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='region',
            field=models.CharField(choices=[('220', 'Iran'), ('360', 'India'), ('560', 'Europe')], default='IR', max_length=3),
        ),
    ]
