# Generated by Django 3.2.5 on 2022-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0003_auto_20220327_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x000001DC6FB31D60>'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x000001DC6FB31D60>'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='Codm/media/account_pictures/<django.db.models.query_utils.DeferredAttribute object at 0x000001DC6FB31D60>'),
        ),
    ]
