# Generated by Django 3.2.5 on 2022-02-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0003_auto_20220209_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
