# Generated by Django 3.2.5 on 2022-01-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0004_auto_20220126_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Codm/static/account_pictures'),
        ),
        migrations.AlterField(
            model_name='link',
            name='Type',
            field=models.CharField(choices=[('activision', 'Activision'), ('facebook', 'Facebook'), ('gmail', 'Gmail'), ('apple_id', 'Apple_ID'), ('line', 'Line')], default='Activision', max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount'),
        ),
    ]
