# Generated by Django 3.2.5 on 2022-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('nf', 'NotFinished'), ('f', 'Finished')], default='nf', max_length=2),
        ),
    ]
