# Generated by Django 3.2.5 on 2022-01-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0005_auto_20220129_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codaccount',
            name='pub_date',
        ),
    ]
