# Generated by Django 3.2.5 on 2022-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0005_auto_20220327_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='account_pictures/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=300, upload_to='account_pictures/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=500, null=True, upload_to='account_videos/'),
        ),
    ]
