# Generated by Django 3.2.5 on 2022-02-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0005_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.AddField(
            model_name='codaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Codm.order'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Codm.cart'),
        ),
    ]
