# Generated by Django 3.2.5 on 2022-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0006_auto_20220327_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codaccount',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='account_pictures/'),
        ),
    ]
