# Generated by Django 3.2.5 on 2022-02-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0006_auto_20220210_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codaccount',
            old_name='account',
            new_name='order',
        ),
    ]
