# Generated by Django 3.2.5 on 2022-02-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Codm', '0006_remove_codaccount_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='codaccount',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='final_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='w4p', max_length=10),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('w4p', 'WairForPublish')], default='w4p', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('factor_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codm.codaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
    ]
