# Generated by Django 3.2.5 on 2022-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0009_alter_codaccount_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codaccount',
            name='cart',
        ),
        migrations.AddField(
            model_name='codaccount',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='Codm.Cart'),
        ),
    ]
