# Generated by Django 3.2.5 on 2022-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0010_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('sold', 'فروخته شد'), ('w4p', 'در انتظار تایید'), ('canceled', 'لغو شده')], default='w4p', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=300, upload_to='account_pictures/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=500, null=True, upload_to='account_videos/'),
        ),
    ]
