# Generated by Django 3.2.5 on 2022-02-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0010_auto_20220211_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codaccount',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, to='Codm.CodAccount'),
        ),
    ]
