# Generated by Django 3.2.5 on 2022-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0013_auto_20220427_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='battle_pass',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='بتل پس ها'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='battle_ranked',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رنک بتل'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='c',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد C'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='cp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد CP'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='description',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='توضیحات فروشنده'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='level',
            field=models.IntegerField(default=1, verbose_name='لول'),
        ),
        migrations.AlterField(
            model_name='codaccount',
            name='multi_ranked',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رنک مولتی'),
        ),
    ]
