# Generated by Django 3.2.5 on 2022-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0014_auto_20220427_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaccount',
            name='region',
            field=models.CharField(choices=[('220', 'هند'), ('360', 'ایران'), ('560', 'اروپا')], default='IR', max_length=3, verbose_name='ریجن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
