# Generated by Django 3.2.5 on 2022-04-27 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Codm', '0015_auto_20220427_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAccount',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('factor_number', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('final_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('w4c', 'ثبت شده'), ('w4a', 'در انتظار پاسخگویی فروشنده'), ('w4r', 'در انتظار ارسال اطلاعات توسط فروشنده'), ('rinfo', 'ویرایش و آماده سازی اطلاعات توسط سایت'), ('g2b', 'تایید اطلاعات توسط خریدار'), ('cl', 'لغو شده'), ('dn', 'تکمیل شده')], default='w4c', max_length=5)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Codm.orderaccount'),
        ),
    ]
