# Generated by Django 3.2.5 on 2022-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0016_auto_20220428_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaccount',
            name='cl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='dn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='g2b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='rinfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='w4a',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='w4c',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='w4r',
            field=models.BooleanField(default=False),
        ),
    ]
