# Generated by Django 4.0.4 on 2022-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codm', '0017_auto_20220428_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaccount',
            name='status',
            field=models.CharField(choices=[('w4c', 'ثبت سفارش'), ('w4a', 'در انتظار پاسخگویی فروشنده'), ('w4r', 'در انتظار ارسال اطلاعات توسط فروشنده'), ('rinfo', 'ویرایش و آماده سازی اطلاعات توسط سایت'), ('g2b', 'تایید اطلاعات توسط خریدار'), ('cl', 'لغو شده'), ('dn', 'تکمیل سفارش')], default='w4c', max_length=5),
        ),
    ]
