# Generated by Django 3.2.5 on 2022-03-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=900, null=True)),
                ('image', models.ImageField(null=True, upload_to='Products/static/Products/product_picture')),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NA', 'NotAvailable')], default='AV', max_length=2)),
                ('price', models.IntegerField(default=30000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.group')),
            ],
        ),
        migrations.CreateModel(
            name='EP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('product', models.ManyToManyField(to='Products.Product')),
            ],
        ),
    ]
