# Generated by Django 3.2.5 on 2022-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=5000, null=True, upload_to='Products/media/Products/product_picture/None/'),
        ),
    ]
