# Generated by Django 3.2.5 on 2022-04-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0004_auto_20220418_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='activition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='apple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='gmail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='supercell',
            field=models.BooleanField(default=False),
        ),
    ]
