# Generated by Django 3.2.5 on 2022-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20220422_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ep',
            name='product',
            field=models.ManyToManyField(null=True, to='Products.Product'),
        ),
    ]
