# Generated by Django 3.2.5 on 2022-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_ep_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='Type',
            field=models.CharField(choices=[('activision', 'اکتیویژن'), ('facebook', 'فیسبوک'), ('gmail', 'جیمیل'), ('apple', 'اپل آی-دی'), ('supercell', 'سوپرسل')], default='Activision', max_length=10),
        ),
        migrations.AlterField(
            model_name='ep',
            name='product',
            field=models.ManyToManyField(blank=True, to='Products.Product'),
        ),
        migrations.AlterField(
            model_name='group',
            name='activition',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='apple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='gmail',
            field=models.BooleanField(default=False),
        ),
    ]
