# Generated by Django 3.2.5 on 2022-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_ep_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ep',
            name='code',
        ),
    ]
