# Generated by Django 3.2.5 on 2022-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_ep_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ep',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(blank=True, to='Products.EP'),
        ),
    ]
