# Generated by Django 3.2.5 on 2022-04-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_auto_20220423_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='ep',
        ),
    ]
